[34m[1mwandb[39m[22m: Downloading large artifact model-B_eval_loss:latest, 168.79MB. 8 files...
[34m[1mwandb[39m[22m:   8 of 8 files downloaded.
Done. 0:0:0.4
Traceback (most recent call last):
  File "/home/geo_llm/llama3-finetune/HuMob_wandb.py", line 169, in <module>
    trainer.train(resume_from_checkpoint=artifact_dir)
  File "<string>", line 100, in train
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/trainer_callback.py", line 149, in load_from_json
    with open(json_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/geo_llm/llama3-finetune/artifacts/model-B_eval_loss:v19/trainer_state.json'